// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
)

const countCertTypes = `-- name: CountCertTypes :one

SELECT COUNT (*) AS count_cert_types FROM certificate_types
`

func (q *Queries) CountCertTypes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCertTypes)
	var count_cert_types int64
	err := row.Scan(&count_cert_types)
	return count_cert_types, err
}

const countCertificates = `-- name: CountCertificates :one

SELECT COUNT (*) AS count_certificates FROM certificates
`

func (q *Queries) CountCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCertificates)
	var count_certificates int64
	err := row.Scan(&count_certificates)
	return count_certificates, err
}
