// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCert = `-- name: CreateCert :one
INSERT INTO certificates (id, created_at, updated_at, cert_type_id, cert_number, issuer, issued_date)
VALUES (
           $1, $2, $3, $4, $5, $6, $7
       )
RETURNING id, created_at, updated_at, name, cert_number, issuer, issued_date, cert_type_id, alternative_name, remarks
`

type CreateCertParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CertTypeID uuid.NullUUID
	CertNumber string
	Issuer     string
	IssuedDate time.Time
}

func (q *Queries) CreateCert(ctx context.Context, arg CreateCertParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCert,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CertTypeID,
		arg.CertNumber,
		arg.Issuer,
		arg.IssuedDate,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.CertNumber,
		&i.Issuer,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
	)
	return i, err
}

const getCertFromId = `-- name: GetCertFromId :one
SELECT id, created_at, updated_at, name, cert_number, issuer, issued_date, cert_type_id, alternative_name, remarks FROM certificates WHERE id=$1
`

func (q *Queries) GetCertFromId(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertFromId, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.CertNumber,
		&i.Issuer,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
	)
	return i, err
}

const getCerts = `-- name: GetCerts :many
SELECT id, created_at, updated_at, name, cert_number, issuer, issued_date, cert_type_id, alternative_name, remarks FROM certificates
`

func (q *Queries) GetCerts(ctx context.Context) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.CertNumber,
			&i.Issuer,
			&i.IssuedDate,
			&i.CertTypeID,
			&i.AlternativeName,
			&i.Remarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
