// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package database

import (
	"context"
)

const resetCertTypes = `-- name: ResetCertTypes :exec
DELETE from certificate_types
`

func (q *Queries) ResetCertTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCertTypes)
	return err
}

const resetCerts = `-- name: ResetCerts :exec
DELETE from certificates
`

func (q *Queries) ResetCerts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCerts)
	return err
}
