// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cert_types.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCertType = `-- name: CreateCertType :one
INSERT INTO certificate_types (id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by
`

type CreateCertTypeParams struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	ShortName            string
	StcwReference        sql.NullString
	NormalValidityMonths sql.NullInt32
	Status               string
	CreatedBy            uuid.NullUUID
}

func (q *Queries) CreateCertType(ctx context.Context, arg CreateCertTypeParams) (CertificateType, error) {
	row := q.db.QueryRowContext(ctx, createCertType,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.ShortName,
		arg.StcwReference,
		arg.NormalValidityMonths,
		arg.Status,
		arg.CreatedBy,
	)
	var i CertificateType
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShortName,
		&i.StcwReference,
		&i.NormalValidityMonths,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const deleteCertType = `-- name: DeleteCertType :exec
DELETE FROM certificate_types WHERE id = $1
`

func (q *Queries) DeleteCertType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCertType, id)
	return err
}

const getCertTypeFromId = `-- name: GetCertTypeFromId :one
SELECT id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by FROM certificate_types WHERE id=$1
`

func (q *Queries) GetCertTypeFromId(ctx context.Context, id uuid.UUID) (CertificateType, error) {
	row := q.db.QueryRowContext(ctx, getCertTypeFromId, id)
	var i CertificateType
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShortName,
		&i.StcwReference,
		&i.NormalValidityMonths,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const getCertTypeFromName = `-- name: GetCertTypeFromName :one
SELECT id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by FROM certificate_types WHERE name=$1
`

func (q *Queries) GetCertTypeFromName(ctx context.Context, name string) (CertificateType, error) {
	row := q.db.QueryRowContext(ctx, getCertTypeFromName, name)
	var i CertificateType
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShortName,
		&i.StcwReference,
		&i.NormalValidityMonths,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const getCertTypes = `-- name: GetCertTypes :many
SELECT id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by FROM certificate_types
`

func (q *Queries) GetCertTypes(ctx context.Context) ([]CertificateType, error) {
	rows, err := q.db.QueryContext(ctx, getCertTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateType
	for rows.Next() {
		var i CertificateType
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ShortName,
			&i.StcwReference,
			&i.NormalValidityMonths,
			&i.Status,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCertTypesForUser = `-- name: GetCertTypesForUser :many
SELECT id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by FROM certificate_types
WHERE status = 'approved' OR created_by = $1
`

func (q *Queries) GetCertTypesForUser(ctx context.Context, createdBy uuid.NullUUID) ([]CertificateType, error) {
	rows, err := q.db.QueryContext(ctx, getCertTypesForUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateType
	for rows.Next() {
		var i CertificateType
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ShortName,
			&i.StcwReference,
			&i.NormalValidityMonths,
			&i.Status,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertType = `-- name: UpdateCertType :one
UPDATE certificate_types
SET
    name = COALESCE($2, name),
    short_name = COALESCE($3, short_name),
    stcw_reference = COALESCE($4, stcw_reference),
    normal_validity_months = COALESCE($5, normal_validity_months),
    status = COALESCE($6, status),
    updated_at = NOW()
WHERE id=$1
RETURNING id, created_at, updated_at, name, short_name, stcw_reference, normal_validity_months, status, created_by
`

type UpdateCertTypeParams struct {
	ID                   uuid.UUID
	Name                 sql.NullString
	ShortName            sql.NullString
	StcwReference        sql.NullString
	NormalValidityMonths sql.NullInt32
	Status               sql.NullString
}

func (q *Queries) UpdateCertType(ctx context.Context, arg UpdateCertTypeParams) (CertificateType, error) {
	row := q.db.QueryRowContext(ctx, updateCertType,
		arg.ID,
		arg.Name,
		arg.ShortName,
		arg.StcwReference,
		arg.NormalValidityMonths,
		arg.Status,
	)
	var i CertificateType
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShortName,
		&i.StcwReference,
		&i.NormalValidityMonths,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const updateCertTypeReferences = `-- name: UpdateCertTypeReferences :exec
UPDATE certificates SET cert_type_id = $2 WHERE cert_type_id = $1
`

type UpdateCertTypeReferencesParams struct {
	CertTypeID   uuid.UUID
	CertTypeID_2 uuid.UUID
}

func (q *Queries) UpdateCertTypeReferences(ctx context.Context, arg UpdateCertTypeReferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateCertTypeReferences, arg.CertTypeID, arg.CertTypeID_2)
	return err
}
