// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCert = `-- name: CreateCert :one
INSERT INTO certificates (id, created_at, updated_at, user_id, cert_type_id, cert_number, issuer_id, issued_date, alternative_name, remarks)
VALUES (
           $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
       )
RETURNING id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id
`

type CreateCertParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UserID          uuid.UUID
	CertTypeID      uuid.UUID
	CertNumber      string
	IssuerID        uuid.UUID
	IssuedDate      time.Time
	AlternativeName sql.NullString
	Remarks         sql.NullString
}

func (q *Queries) CreateCert(ctx context.Context, arg CreateCertParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCert,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.CertTypeID,
		arg.CertNumber,
		arg.IssuerID,
		arg.IssuedDate,
		arg.AlternativeName,
		arg.Remarks,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertNumber,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
		&i.IssuerID,
		&i.UserID,
	)
	return i, err
}

const getCertFromId = `-- name: GetCertFromId :one
SELECT id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id FROM certificates WHERE id=$1 AND user_id=$2
`

type GetCertFromIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCertFromId(ctx context.Context, arg GetCertFromIdParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertFromId, arg.ID, arg.UserID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertNumber,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
		&i.IssuerID,
		&i.UserID,
	)
	return i, err
}

const getCerts = `-- name: GetCerts :many
SELECT id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id FROM certificates WHERE user_id=$1
`

func (q *Queries) GetCerts(ctx context.Context, userID uuid.UUID) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getCerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertNumber,
			&i.IssuedDate,
			&i.CertTypeID,
			&i.AlternativeName,
			&i.Remarks,
			&i.IssuerID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificates
SET
    cert_number=COALESCE($2, cert_number),
    issued_date=COALESCE($3, issued_date),
    cert_type_id=COALESCE($4, cert_type_id),
    alternative_name=COALESCE($5, alternative_name),
    remarks=COALESCE($6, remarks),
    issuer_id=COALESCE($7, issuer_id),
    updated_at=NOW()
WHERE id=$1
RETURNING id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id
`

type UpdateCertificateParams struct {
	ID              uuid.UUID
	CertNumber      sql.NullString
	IssuedDate      sql.NullTime
	CertTypeID      uuid.NullUUID
	AlternativeName sql.NullString
	Remarks         sql.NullString
	IssuerID        uuid.NullUUID
}

func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, updateCertificate,
		arg.ID,
		arg.CertNumber,
		arg.IssuedDate,
		arg.CertTypeID,
		arg.AlternativeName,
		arg.Remarks,
		arg.IssuerID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertNumber,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
		&i.IssuerID,
		&i.UserID,
	)
	return i, err
}
