// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCert = `-- name: CreateCert :one
INSERT INTO certificates (id, created_at, updated_at, cert_type_id, cert_number, issuer_id, issued_date, alternative_name, remarks)
VALUES (
           $1, $2, $3, $4, $5, $6, $7, $8, $9
       )
RETURNING id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id
`

type CreateCertParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CertTypeID      uuid.UUID
	CertNumber      string
	IssuerID        uuid.UUID
	IssuedDate      time.Time
	AlternativeName sql.NullString
	Remarks         sql.NullString
}

func (q *Queries) CreateCert(ctx context.Context, arg CreateCertParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCert,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CertTypeID,
		arg.CertNumber,
		arg.IssuerID,
		arg.IssuedDate,
		arg.AlternativeName,
		arg.Remarks,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertNumber,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
		&i.IssuerID,
		&i.UserID,
	)
	return i, err
}

const getCertFromId = `-- name: GetCertFromId :one
SELECT id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id FROM certificates WHERE id=$1
`

func (q *Queries) GetCertFromId(ctx context.Context, id uuid.UUID) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertFromId, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CertNumber,
		&i.IssuedDate,
		&i.CertTypeID,
		&i.AlternativeName,
		&i.Remarks,
		&i.IssuerID,
		&i.UserID,
	)
	return i, err
}

const getCerts = `-- name: GetCerts :many
SELECT id, created_at, updated_at, cert_number, issued_date, cert_type_id, alternative_name, remarks, issuer_id, user_id FROM certificates
`

func (q *Queries) GetCerts(ctx context.Context) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertNumber,
			&i.IssuedDate,
			&i.CertTypeID,
			&i.AlternativeName,
			&i.Remarks,
			&i.IssuerID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
