// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dummy_records.sql

package sqlc

import (
	"context"
)

const createDummyCertTypes = `-- name: CreateDummyCertTypes :exec

INSERT INTO certificate_types (
    id,
    name,
    short_name,
    stcw_reference,
    normal_validity_months,
    status,
    created_at,
    updated_at
) VALUES
(gen_random_uuid(), 'Certificate of Competency - Deck - Chief Mate Unlimited', 'CoC-CM', 'A-II / 2', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Certificate of Competency - Deck - OOW Unlimited', 'CoC-OOW', 'A-II / 1', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Certificate of Competency - Deck - Master Unlimited', 'CoC-MS', 'A-II / 2', 60, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Seafarer Medical - UK - ENG1', 'ENG1', 'A-I / 9', 24, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Seafarer Medical', 'MED', 'A-I / 9', 24, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'GMDSS General Operator', 'GMDSS', 'A-IV / 2', 60, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Basic Training STCW', 'BT', 'A-VI / 1', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Personal Survival Techniques', 'PST', 'A-VI / 1-1', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Fire Fighting & Prevention', 'FFP', 'A-VI / 1-2', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Elementary First Aid', 'EFA', 'A-VI / 1-3', NULL, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Personal Safety & Social Responsibility', 'PSSR', 'A-VI / 1-4', NULL, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Advanced Firefighting Update', 'AFF-U', 'A-VI / 3', 60, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Tanker Firefighting', 'TFF', 'A-V / 1', 60, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Proficiency in Survival Craft and Rescue Boats (Except Fast Rescue Boats)', 'PSCRB', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Survival Craft and Rescue Boats (Except Fast Rescue Boats) Update', 'PSCRB-U', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Fast Rescue Boats Update', 'FRC-U', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Proficiency in Medical First Aid', 'MFA', 'A-VI / 4-1', NULL, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Medical Care', 'PMC', 'A-VI / 4-2', NULL, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Medical Care Update', 'PMC-U', 'A-VI / 4-2', NULL, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Proficiency in Security Awareness', 'PSA', 'A-VI / 6-1', NULL, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Designated Security Duties', 'DSD', 'A-VI / 6-2', NULL, 'approved', NOW(), NOW()),

(gen_random_uuid(), 'Proficiency in Medical Care Onboard', 'MCOB', 'A-VI / 4-2', 60, 'approved', NOW(), NOW()),
(gen_random_uuid(), 'Proficiency in Medical Care Onboard Update', 'MCOBU', 'A-VI / 4-2', 60, 'approved', NOW(), NOW())
`

// CoC
// Medical
// Radio
// Basic Training
// Advanced Fire
// Tanker
// Survival Craft
// Medical Proficiency
// Security
// Onboard Medical
func (q *Queries) CreateDummyCertTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyCertTypes)
	return err
}

const createDummyIssuers = `-- name: CreateDummyIssuers :exec


INSERT INTO issuers (
    id,
    name,
    country,
    website,
    created_at,
    updated_at
) VALUES
      (gen_random_uuid(), 'Maritime & Coastguard Agency (MCA)', 'GB', 'https://www.gov.uk/government/organisations/maritime-and-coastguard-agency', NOW(), NOW()),
      (gen_random_uuid(), 'Warsash Maritime Academy (WMA)', 'GB', 'https://maritime.solent.ac.uk/', NOW(), NOW()),
      (gen_random_uuid(), 'Maritime Skills Academy (MSA)', 'GB', 'https://www.maritimeskillsacademy.com/', NOW(), NOW()),
      (gen_random_uuid(), 'Stream Marine Training (SMT)', 'GB', 'https://streammarinetraining.com/', NOW(), NOW()),
      (gen_random_uuid(), 'Medical Support Offshore (MSOS)', 'GB', 'https://www.msos.org.uk/', NOW(), NOW()),
      (gen_random_uuid(), 'Fire-Aid Academy', 'GB', 'https://fireaid.com/', NOW(), NOW()),
      (gen_random_uuid(), 'Marina', 'PH', NULL, NOW(), NOW())
`

// one-time setup (safe to run repeatedly)
func (q *Queries) CreateDummyIssuers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyIssuers)
	return err
}
