// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dummy_records.sql

package sqlc

import (
	"context"
)

const createDummyCertTypes = `-- name: CreateDummyCertTypes :exec

INSERT INTO certificate_types (
    id,
    name,
    short_name,
    stcw_reference,
    normal_validity_months,
    status,
    created_at,
    updated_at
) VALUES
('10000000-0000-0000-0000-000000000001', 'Certificate of Competency - Deck - Chief Mate Unlimited', 'CoC-CM', 'A-II / 2', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000002', 'Certificate of Competency - Deck - OOW Unlimited', 'CoC-OOW', 'A-II / 1', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000003', 'Certificate of Competency - Deck - Master Unlimited', 'CoC-MS', 'A-II / 2', 60, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000004', 'Seafarer Medical - UK - ENG1', 'ENG1', 'A-I / 9', 24, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000005', 'Seafarer Medical', 'MED', 'A-I / 9', 24, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000006', 'GMDSS General Operator', 'GMDSS', 'A-IV / 2', 60, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000007', 'Basic Training STCW', 'BT', 'A-VI / 1', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000008', 'Personal Survival Techniques', 'PST', 'A-VI / 1-1', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000009', 'Fire Fighting & Prevention', 'FFP', 'A-VI / 1-2', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000010', 'Elementary First Aid', 'EFA', 'A-VI / 1-3', NULL, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000011', 'Personal Safety & Social Responsibility', 'PSSR', 'A-VI / 1-4', NULL, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000012', 'Advanced Firefighting Update', 'AFF-U', 'A-VI / 3', 60, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000013', 'Tanker Firefighting', 'TFF', 'A-V / 1', 60, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000014', 'Proficiency in Survival Craft and Rescue Boats (Except Fast Rescue Boats)', 'PSCRB', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000015', 'Proficiency in Survival Craft and Rescue Boats (Except Fast Rescue Boats) Update', 'PSCRB-U', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000016', 'Proficiency in Fast Rescue Boats Update', 'FRC-U', 'A-VI / 2-1', 60, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000017', 'Proficiency in Medical First Aid', 'MFA', 'A-VI / 4-1', NULL, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000018', 'Proficiency in Medical Care', 'PMC', 'A-VI / 4-2', NULL, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000019', 'Proficiency in Medical Care Update', 'PMC-U', 'A-VI / 4-2', NULL, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000020', 'Proficiency in Security Awareness', 'PSA', 'A-VI / 6-1', NULL, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000021', 'Proficiency in Designated Security Duties', 'DSD', 'A-VI / 6-2', NULL, 'approved', NOW(), NOW()),

('10000000-0000-0000-0000-000000000022', 'Proficiency in Medical Care Onboard', 'MCOB', 'A-VI / 4-2', 60, 'approved', NOW(), NOW()),
('10000000-0000-0000-0000-000000000023', 'Proficiency in Medical Care Onboard Update', 'MCOBU', 'A-VI / 4-2', 60, 'approved', NOW(), NOW())
`

// CoC
// Medical
// Radio
// Basic Training
// Advanced Fire
// Tanker
// Survival Craft
// Medical Proficiency
// Security
// Onboard Medical
func (q *Queries) CreateDummyCertTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyCertTypes)
	return err
}

const createDummyCertificates = `-- name: CreateDummyCertificates :exec

INSERT INTO certificates (
    id,
    created_at,
    updated_at,
    user_id,
    cert_type_id,
    cert_number,
    issuer_id,
    issued_date
)
VALUES

    -- User 003:
    -- Existing certificate purely to make this user ineligible
    -- for the 7-day no-certificates reminder.
    (
        '20000000-0000-0000-0000-000000000001',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000003',
        '10000000-0000-0000-0000-000000000001',
        'TEST-003-001',
        '10000000-0000-0000-0000-000000000001',
        NOW()
    ),

    -- User 007:
    -- Existing certificate purely to make this user ineligible
    -- for the 1-month no-certificates reminder.
    (
        '20000000-0000-0000-0000-000000000002',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000007',
        '10000000-0000-0000-0000-000000000001',
        'TEST-007-001',
        '10000000-0000-0000-0000-000000000001',
        NOW()
    ),

    ----------------------------------------------------------------
    -- User 009: certificate-expiry summary fixtures
    ----------------------------------------------------------------

    -- ENG1 has 24-month normal validity.
    -- Issued 25 months ago => nominally expired about 1 month ago.
    (
        '20000000-0000-0000-0000-000000000003',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000009',
        '10000000-0000-0000-0000-000000000004',
        'EXP-EXPIRED-001',
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '25 months'
    ),

    -- ENG1: issued 23 months 15 days ago.
    -- Nominal expiry is about 15 days from now.
    -- EXPECTED BUCKET: next month.
    (
        '20000000-0000-0000-0000-000000000004',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000009',
        '10000000-0000-0000-0000-000000000004',
        'EXP-1MONTH-001',
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '23 months 15 days'
    ),

    -- ENG1: issued 20 months ago.
    -- Nominal expiry is about 4 months from now.
    -- EXPECTED BUCKET: next 6 months.
    (
        '20000000-0000-0000-0000-000000000005',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000009',
        '10000000-0000-0000-0000-000000000004',
        'EXP-6MONTH-001',
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '20 months'
    ),

    -- ENG1: issued 16 months ago.
    -- Nominal expiry is about 8 months from now.
    -- EXPECTED BUCKET: next year.
    (
        '20000000-0000-0000-0000-000000000006',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000009',
        '10000000-0000-0000-0000-000000000004',
        'EXP-1YEAR-001',
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '16 months'
    ),

    -- ENG1: issued recently.
    -- Nominal expiry is well over a year away.
    -- EXPECTED: not included in expiry summary.
    (
        '20000000-0000-0000-0000-000000000007',
        NOW(),
        NOW(),
        '10000000-0000-0000-0000-000000000009',
        '10000000-0000-0000-0000-000000000004',
        'EXP-NOT-DUE-001',
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '2 months'
    )
`

func (q *Queries) CreateDummyCertificates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyCertificates)
	return err
}

const createDummyIssuers = `-- name: CreateDummyIssuers :exec


INSERT INTO issuers (
    id,
    name,
    country,
    website,
    created_at,
    updated_at
) VALUES
      ('10000000-0000-0000-0000-000000000001', 'Maritime & Coastguard Agency (MCA)', 'GB', 'https://www.gov.uk/government/organisations/maritime-and-coastguard-agency', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000002', 'Warsash Maritime Academy (WMA)', 'GB', 'https://maritime.solent.ac.uk/', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000003', 'Maritime Skills Academy (MSA)', 'GB', 'https://www.maritimeskillsacademy.com/', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000004', 'Stream Marine Training (SMT)', 'GB', 'https://streammarinetraining.com/', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000005', 'Medical Support Offshore (MSOS)', 'GB', 'https://www.msos.org.uk/', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000006', 'Fire-Aid Academy', 'GB', 'https://fireaid.com/', NOW(), NOW()),
      ('10000000-0000-0000-0000-000000000007', 'Marina', 'PH', NULL, NOW(), NOW())
`

// one-time setup (safe to run repeatedly)
func (q *Queries) CreateDummyIssuers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyIssuers)
	return err
}

const createDummyNotifications = `-- name: CreateDummyNotifications :exec

INSERT INTO notifications (
    id,
    user_id,
    notification_type,
    notification_key,
    status,
    payload,
    scheduled_at,
    created_at,
    updated_at
)
VALUES

    -- User 004 has already received the 7-day reminder.
    (
        gen_random_uuid(),
        '10000000-0000-0000-0000-000000000004',
        'no_certificates_7d',
        'no-certificates:10000000-0000-0000-0000-000000000004:7d',
        'completed',
        '{}'::jsonb,
        NOW() - INTERVAL '1 day',
        NOW() - INTERVAL '1 day',
        NOW()
    ),

    -- User 005 is old enough for the 1-month reminder.
    -- Seed their 7-day reminder so only the 1-month generator
    -- should create something new for them.
    (
        gen_random_uuid(),
        '10000000-0000-0000-0000-000000000005',
        'no_certificates_7d',
        'no-certificates:10000000-0000-0000-0000-000000000005:7d',
        'completed',
        '{}'::jsonb,
        NOW() - INTERVAL '30 days',
        NOW() - INTERVAL '30 days',
        NOW()
    ),

    -- User 008 has already had the 7-day reminder.
    (
        gen_random_uuid(),
        '10000000-0000-0000-0000-000000000008',
        'no_certificates_7d',
        'no-certificates:10000000-0000-0000-0000-000000000008:7d',
        'completed',
        '{}'::jsonb,
        NOW() - INTERVAL '35 days',
        NOW() - INTERVAL '35 days',
        NOW()
    ),

    -- User 008 has also already had the 1-month reminder.
    -- This tests that the 1-month generator does not duplicate it.
    (
        gen_random_uuid(),
        '10000000-0000-0000-0000-000000000008',
        'no_certificates_1m',
        'no-certificates:10000000-0000-0000-0000-000000000008:1m',
        'completed',
        '{}'::jsonb,
        NOW() - INTERVAL '5 days',
        NOW() - INTERVAL '5 days',
        NOW()
    )
`

func (q *Queries) CreateDummyNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyNotifications)
	return err
}

const createDummyUsers = `-- name: CreateDummyUsers :exec


INSERT INTO users (
    id,
    created_at,
    updated_at,
    forename,
    surname,
    email,
    nationality,
    email_consent
)
VALUES
    (
        '10000000-0000-0000-0000-000000000001',
        NOW() - INTERVAL '10 days',
        NOW(),
        'Test',
        'Eligible7Day',
        'hello@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000002',
        NOW() - INTERVAL '3 days',
        NOW(),
        'Test',
        'TooYoung',
        'hello1@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000003',
        NOW() - INTERVAL '10 days',
        NOW(),
        'Test',
        'HasCertificate7Day',
        'hello2@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000004',
        NOW() - INTERVAL '10 days',
        NOW(),
        'Test',
        'AlreadyNotified7Day',
        'hello3@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000005',
        NOW() - INTERVAL '45 days',
        NOW(),
        'Test',
        'Eligible1Month',
        'adam.james624@gmail.com',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000006',
        NOW() - INTERVAL '20 days',
        NOW(),
        'Test',
        'SevenDayOnly',
        'adamjames624@gmail.com',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000007',
        NOW() - INTERVAL '45 days',
        NOW(),
        'Test',
        'HasCertificate1Month',
        'hello6@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000008',
        NOW() - INTERVAL '45 days',
        NOW(),
        'Test',
        'AlreadyNotifiedBoth',
        'hello7@seacert.app',
        'GB',
        TRUE
    ),
    (
        '10000000-0000-0000-0000-000000000009',
        NOW() - INTERVAL '2 years',
        NOW(),
        'Test',
        'ExpirySummary',
        'hello8@seacert.app',
        'GB',
        TRUE
    )
`

// Notification / expiry test users
//
// 001: 10 days old, no certificates
//
//	EXPECTED:
//	- eligible for no_certificates_7d
//	- NOT eligible for no_certificates_1m
//
// 002: 3 days old, no certificates
//
//	EXPECTED:
//	- eligible for neither reminder
//
// 003: 10 days old, has certificate
//
//	EXPECTED:
//	- eligible for neither reminder
//
// 004: 10 days old, no certificates, existing 7d notification
//
//	EXPECTED:
//	- no new 7d notification
//
// 005: 45 days old, no certificates, existing 7d notification
//
//	EXPECTED:
//	- no new 7d notification
//	- eligible for no_certificates_1m
//
// 006: 20 days old, no certificates
//
//	EXPECTED:
//	- eligible for no_certificates_7d
//	- NOT eligible for no_certificates_1m
//
// 007: 45 days old, has certificate
//
//	EXPECTED:
//	- eligible for neither reminder
//
// 008: 45 days old, no certificates, already has both notifications
//
//	EXPECTED:
//	- no new notification
//
// 009: established user with multiple certificates
//
//	EXPECTED:
//	- used later for certificate-expiry summary testing
//	- no no-certificate reminders
func (q *Queries) CreateDummyUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDummyUsers)
	return err
}
