// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_deliveries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEmailDelivery = `-- name: CreateEmailDelivery :one
INSERT INTO email_deliveries (id, notification_id, recipient, provider, attempt)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, notification_id, recipient, provider, provider_message_id, status, attempt, error_message, sent_at, created_at
`

type CreateEmailDeliveryParams struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Recipient      string
	Provider       string
	Attempt        int32
}

func (q *Queries) CreateEmailDelivery(ctx context.Context, arg CreateEmailDeliveryParams) (EmailDelivery, error) {
	row := q.db.QueryRowContext(ctx, createEmailDelivery,
		arg.ID,
		arg.NotificationID,
		arg.Recipient,
		arg.Provider,
		arg.Attempt,
	)
	var i EmailDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.Attempt,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailDeliveriesForNotification = `-- name: GetEmailDeliveriesForNotification :many
SELECT id, notification_id, recipient, provider, provider_message_id, status, attempt, error_message, sent_at, created_at
FROM email_deliveries
WHERE notification_id = $1
ORDER BY attempt ASC, created_at ASC
`

func (q *Queries) GetEmailDeliveriesForNotification(ctx context.Context, notificationID uuid.UUID) ([]EmailDelivery, error) {
	rows, err := q.db.QueryContext(ctx, getEmailDeliveriesForNotification, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailDelivery
	for rows.Next() {
		var i EmailDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Recipient,
			&i.Provider,
			&i.ProviderMessageID,
			&i.Status,
			&i.Attempt,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailDeliveryFailed = `-- name: MarkEmailDeliveryFailed :one
UPDATE email_deliveries
SET status = 'failed', error_message = $2
WHERE id = $1
RETURNING id, notification_id, recipient, provider, provider_message_id, status, attempt, error_message, sent_at, created_at
`

type MarkEmailDeliveryFailedParams struct {
	ID           uuid.UUID
	ErrorMessage sql.NullString
}

func (q *Queries) MarkEmailDeliveryFailed(ctx context.Context, arg MarkEmailDeliveryFailedParams) (EmailDelivery, error) {
	row := q.db.QueryRowContext(ctx, markEmailDeliveryFailed, arg.ID, arg.ErrorMessage)
	var i EmailDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.Attempt,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailDeliverySent = `-- name: MarkEmailDeliverySent :one
UPDATE email_deliveries
SET status = 'sent', provider_message_id = $2, sent_at = NOW()
WHERE id = $1
RETURNING id, notification_id, recipient, provider, provider_message_id, status, attempt, error_message, sent_at, created_at
`

type MarkEmailDeliverySentParams struct {
	ID                uuid.UUID
	ProviderMessageID sql.NullString
}

func (q *Queries) MarkEmailDeliverySent(ctx context.Context, arg MarkEmailDeliverySentParams) (EmailDelivery, error) {
	row := q.db.QueryRowContext(ctx, markEmailDeliverySent, arg.ID, arg.ProviderMessageID)
	var i EmailDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Recipient,
		&i.Provider,
		&i.ProviderMessageID,
		&i.Status,
		&i.Attempt,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}
