// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issuers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIssuer = `-- name: CreateIssuer :one

INSERT INTO issuers (id, created_at, updated_at, name, country, website)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, country, website
`

type CreateIssuerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Country   sql.NullString
	Website   sql.NullString
}

func (q *Queries) CreateIssuer(ctx context.Context, arg CreateIssuerParams) (Issuer, error) {
	row := q.db.QueryRowContext(ctx, createIssuer,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Country,
		arg.Website,
	)
	var i Issuer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Country,
		&i.Website,
	)
	return i, err
}

const getIssuerById = `-- name: GetIssuerById :one
SELECT id, created_at, updated_at, name, country, website FROM issuers WHERE id = $1
`

func (q *Queries) GetIssuerById(ctx context.Context, id uuid.UUID) (Issuer, error) {
	row := q.db.QueryRowContext(ctx, getIssuerById, id)
	var i Issuer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Country,
		&i.Website,
	)
	return i, err
}

const getIssuerByName = `-- name: GetIssuerByName :one
SELECT id, created_at, updated_at, name, country, website FROM issuers WHERE name = $1
`

func (q *Queries) GetIssuerByName(ctx context.Context, name string) (Issuer, error) {
	row := q.db.QueryRowContext(ctx, getIssuerByName, name)
	var i Issuer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Country,
		&i.Website,
	)
	return i, err
}

const getIssuers = `-- name: GetIssuers :many
SELECT id, created_at, updated_at, name, country, website FROM issuers
`

func (q *Queries) GetIssuers(ctx context.Context) ([]Issuer, error) {
	rows, err := q.db.QueryContext(ctx, getIssuers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issuer
	for rows.Next() {
		var i Issuer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Country,
			&i.Website,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssuer = `-- name: UpdateIssuer :one
UPDATE issuers
SET
    name = COALESCE($2, name),
    country = COALESCE($3, country),
    website = COALESCE($4, website)
WHERE id = $1
RETURNING id, created_at, updated_at, name, country, website
`

type UpdateIssuerParams struct {
	ID      uuid.UUID
	Name    sql.NullString
	Country sql.NullString
	Website sql.NullString
}

func (q *Queries) UpdateIssuer(ctx context.Context, arg UpdateIssuerParams) (Issuer, error) {
	row := q.db.QueryRowContext(ctx, updateIssuer,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.Website,
	)
	var i Issuer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Country,
		&i.Website,
	)
	return i, err
}
