// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Certificate struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CertNumber      string
	IssuedDate      time.Time
	CertTypeID      uuid.UUID
	AlternativeName sql.NullString
	Remarks         sql.NullString
	IssuerID        uuid.UUID
}

type CertificateType struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	ShortName            string
	StcwReference        sql.NullString
	NormalValidityMonths sql.NullInt32
}

type Issuer struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Country   sql.NullString
	Website   sql.NullString
}
