// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Certificate struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CertNumber      string
	IssuedDate      time.Time
	CertTypeID      uuid.UUID
	AlternativeName sql.NullString
	Remarks         sql.NullString
	IssuerID        uuid.UUID
	UserID          uuid.UUID
	ManualExpiry    sql.NullTime
	Deleted         bool
	DocumentPath    sql.NullString
}

type CertificateType struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Name                 string
	ShortName            string
	StcwReference        sql.NullString
	NormalValidityMonths sql.NullInt32
	Status               string
	CreatedBy            uuid.NullUUID
}

type CertificateTypeSuccession struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ReplacingCertType   uuid.UUID
	ReplaceableCertType uuid.UUID
	ReplaceReason       SuccessionReason
}

type Issuer struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Country   sql.NullString
	Website   sql.NullString
}

type Seatime struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ShipID         uuid.UUID
	VoyageTypeID   uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StartDate      time.Time
	StartLocation  string
	EndDate        time.Time
	EndLocation    string
	TotalDays      int32
	Company        string
	Capacity       string
	IsWatchkeeping bool
}

type SeatimePeriod struct {
	ID           uuid.UUID
	SeatimeID    uuid.UUID
	PeriodTypeID uuid.UUID
	StartDate    time.Time
	EndDate      time.Time
	Days         int32
	Remarks      sql.NullString
}

type SeatimePeriodType struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Ship struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
}

type ShipType struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Succession struct {
	ID      uuid.UUID
	NewCert uuid.UUID
	OldCert uuid.UUID
	Reason  SuccessionReason
}

type User struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Forename              sql.NullString
	Surname               sql.NullString
	Email                 string
	Nationality           sql.NullString
	EmailConsent          bool
	EmailConsentTimestamp sql.NullTime
	EmailConsentVersion   sql.NullString
	EmailConsentSource    sql.NullString
}

type VoyageType struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}
