// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, notification_type, notification_key, payload, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
`

type CreateNotificationParams struct {
	ID               uuid.UUID
	UserID           uuid.NullUUID
	NotificationType string
	NotificationKey  string
	Payload          json.RawMessage
	ScheduledAt      time.Time
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.NotificationType,
		arg.NotificationKey,
		arg.Payload,
		arg.ScheduledAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.NotificationKey,
		&i.Status,
		&i.Payload,
		&i.ScheduledAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCandidateUsersForExpiryNotification = `-- name: GetCandidateUsersForExpiryNotification :many
SELECT DISTINCT user_id
FROM certificates
WHERE deleted = FALSE
ORDER BY user_id ASC
`

func (q *Queries) GetCandidateUsersForExpiryNotification(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getCandidateUsersForExpiryNotification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByKey = `-- name: GetNotificationByKey :one
SELECT id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
FROM notifications
WHERE notification_key = $1
`

func (q *Queries) GetNotificationByKey(ctx context.Context, notificationKey string) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByKey, notificationKey)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.NotificationKey,
		&i.Status,
		&i.Payload,
		&i.ScheduledAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationsStatusSummary = `-- name: GetNotificationsStatusSummary :many
SELECT status, COUNT(*) AS count
FROM notifications
GROUP BY status
`

type GetNotificationsStatusSummaryRow struct {
	Status string
	Count  int64
}

func (q *Queries) GetNotificationsStatusSummary(ctx context.Context) ([]GetNotificationsStatusSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsStatusSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsStatusSummaryRow
	for rows.Next() {
		var i GetNotificationsStatusSummaryRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
FROM notifications
WHERE status = 'pending' AND scheduled_at <= NOW()
ORDER BY scheduled_at ASC, created_at ASC
`

func (q *Queries) GetPendingNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NotificationType,
			&i.NotificationKey,
			&i.Status,
			&i.Payload,
			&i.ScheduledAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersEligibleForNoCertificates1Month = `-- name: GetUsersEligibleForNoCertificates1Month :many
SELECT u.id
FROM users u
WHERE u.created_at <= NOW() - INTERVAL '1 month'
  AND NOT EXISTS (
      SELECT 1
      FROM certificates c
      WHERE c.user_id = u.id
  )
  AND NOT EXISTS (
      SELECT 1
      FROM notifications n
      WHERE n.user_id = u.id
        AND n.notification_type = 'no_certificates_1m'
  )
`

func (q *Queries) GetUsersEligibleForNoCertificates1Month(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUsersEligibleForNoCertificates1Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersEligibleForNoCertificates7Day = `-- name: GetUsersEligibleForNoCertificates7Day :many
SELECT u.id
FROM users u
WHERE u.created_at <= NOW() - INTERVAL '7 days'
  AND u.created_at >= NOW() - INTERVAL '21 days'
  AND NOT EXISTS (
      SELECT 1
      FROM certificates c
      WHERE c.user_id = u.id
  )
  AND NOT EXISTS (
      SELECT 1
      FROM notifications n
      WHERE n.user_id = u.id
        AND n.notification_type = 'no_certificates_7d'
  )
`

func (q *Queries) GetUsersEligibleForNoCertificates7Day(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUsersEligibleForNoCertificates7Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationCompleted = `-- name: MarkNotificationCompleted :one
UPDATE notifications
SET status = 'completed', processed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
`

func (q *Queries) MarkNotificationCompleted(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationCompleted, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.NotificationKey,
		&i.Status,
		&i.Payload,
		&i.ScheduledAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :one
UPDATE notifications
SET status = 'failed', processed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
`

func (q *Queries) MarkNotificationFailed(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationFailed, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.NotificationKey,
		&i.Status,
		&i.Payload,
		&i.ScheduledAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationProcessing = `-- name: MarkNotificationProcessing :one
UPDATE notifications
SET status = 'processing', updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, notification_type, notification_key, status, payload, scheduled_at, processed_at, created_at, updated_at
`

func (q *Queries) MarkNotificationProcessing(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationProcessing, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NotificationType,
		&i.NotificationKey,
		&i.Status,
		&i.Payload,
		&i.ScheduledAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
