// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_caches.sql

package sqlc

import (
	"context"
	"time"
)

const deleteExpiredPromptCaches = `-- name: DeleteExpiredPromptCaches :exec
DELETE FROM prompt_caches
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredPromptCaches(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPromptCaches)
	return err
}

const getPromptCache = `-- name: GetPromptCache :one
SELECT cache_key, model_name, gemini_cache_name, expires_at, created_at FROM prompt_caches
WHERE cache_key = $1 AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetPromptCache(ctx context.Context, cacheKey string) (PromptCach, error) {
	row := q.db.QueryRowContext(ctx, getPromptCache, cacheKey)
	var i PromptCach
	err := row.Scan(
		&i.CacheKey,
		&i.ModelName,
		&i.GeminiCacheName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPromptCache = `-- name: UpsertPromptCache :exec
INSERT INTO prompt_caches (
    cache_key, model_name, gemini_cache_name, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (cache_key) DO UPDATE SET
    gemini_cache_name = EXCLUDED.gemini_cache_name,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type UpsertPromptCacheParams struct {
	CacheKey        string
	ModelName       string
	GeminiCacheName string
	ExpiresAt       time.Time
}

func (q *Queries) UpsertPromptCache(ctx context.Context, arg UpsertPromptCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPromptCache,
		arg.CacheKey,
		arg.ModelName,
		arg.GeminiCacheName,
		arg.ExpiresAt,
	)
	return err
}
