// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset.sql

package sqlc

import (
	"context"
)

const resetCertTypes = `-- name: ResetCertTypes :exec
DELETE from certificate_types
`

func (q *Queries) ResetCertTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCertTypes)
	return err
}

const resetCerts = `-- name: ResetCerts :exec
DELETE from certificates
`

func (q *Queries) ResetCerts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCerts)
	return err
}

const resetIssuers = `-- name: ResetIssuers :exec
DELETE from issuers
`

func (q *Queries) ResetIssuers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetIssuers)
	return err
}

const resetSeatime = `-- name: ResetSeatime :exec
DELETE from seatime
`

func (q *Queries) ResetSeatime(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSeatime)
	return err
}

const resetSeatimePeriods = `-- name: ResetSeatimePeriods :exec
DELETE from seatime_periods
`

func (q *Queries) ResetSeatimePeriods(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSeatimePeriods)
	return err
}

const resetShips = `-- name: ResetShips :exec
DELETE from ships
`

func (q *Queries) ResetShips(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetShips)
	return err
}

const resetSuccessions = `-- name: ResetSuccessions :exec
DELETE from successions
`

func (q *Queries) ResetSuccessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSuccessions)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE from users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
