// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seatime.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSeatime = `-- name: CreateSeatime :one
INSERT INTO seatime (id, user_id, ship_id, voyage_type_id, created_at, updated_at, start_date, start_location, end_date, end_location, total_days, company, capacity, is_watchkeeping)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, ship_id, voyage_type_id, created_at, updated_at, start_date, start_location, end_date, end_location, total_days, company, capacity, is_watchkeeping
`

type CreateSeatimeParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ShipID         uuid.UUID
	VoyageTypeID   uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	StartDate      time.Time
	StartLocation  string
	EndDate        time.Time
	EndLocation    string
	TotalDays      int32
	Company        string
	Capacity       string
	IsWatchkeeping bool
}

func (q *Queries) CreateSeatime(ctx context.Context, arg CreateSeatimeParams) (Seatime, error) {
	row := q.db.QueryRowContext(ctx, createSeatime,
		arg.ID,
		arg.UserID,
		arg.ShipID,
		arg.VoyageTypeID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartDate,
		arg.StartLocation,
		arg.EndDate,
		arg.EndLocation,
		arg.TotalDays,
		arg.Company,
		arg.Capacity,
		arg.IsWatchkeeping,
	)
	var i Seatime
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShipID,
		&i.VoyageTypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
		&i.StartLocation,
		&i.EndDate,
		&i.EndLocation,
		&i.TotalDays,
		&i.Company,
		&i.Capacity,
		&i.IsWatchkeeping,
	)
	return i, err
}

const createSeatimePeriod = `-- name: CreateSeatimePeriod :one
INSERT INTO seatime_periods (id, seatime_id, period_type_id, start_date, end_date, days, remarks)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, seatime_id, period_type_id, start_date, end_date, days, remarks
`

type CreateSeatimePeriodParams struct {
	ID           uuid.UUID
	SeatimeID    uuid.UUID
	PeriodTypeID uuid.UUID
	StartDate    time.Time
	EndDate      time.Time
	Days         int32
	Remarks      sql.NullString
}

func (q *Queries) CreateSeatimePeriod(ctx context.Context, arg CreateSeatimePeriodParams) (SeatimePeriod, error) {
	row := q.db.QueryRowContext(ctx, createSeatimePeriod,
		arg.ID,
		arg.SeatimeID,
		arg.PeriodTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.Days,
		arg.Remarks,
	)
	var i SeatimePeriod
	err := row.Scan(
		&i.ID,
		&i.SeatimeID,
		&i.PeriodTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.Days,
		&i.Remarks,
	)
	return i, err
}

const createShip = `-- name: CreateShip :one
INSERT INTO ships (id, created_at, updated_at, name, ship_type_id, imo_number, gt, flag, propulsion_power, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at, name, ship_type_id, imo_number, gt, flag, propulsion_power, status, created_by
`

type CreateShipParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
}

func (q *Queries) CreateShip(ctx context.Context, arg CreateShipParams) (Ship, error) {
	row := q.db.QueryRowContext(ctx, createShip,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.ShipTypeID,
		arg.ImoNumber,
		arg.Gt,
		arg.Flag,
		arg.PropulsionPower,
		arg.Status,
		arg.CreatedBy,
	)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShipTypeID,
		&i.ImoNumber,
		&i.Gt,
		&i.Flag,
		&i.PropulsionPower,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const deleteSeatime = `-- name: DeleteSeatime :exec
DELETE FROM seatime WHERE id = $1 AND user_id = $2
`

type DeleteSeatimeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSeatime(ctx context.Context, arg DeleteSeatimeParams) error {
	_, err := q.db.ExecContext(ctx, deleteSeatime, arg.ID, arg.UserID)
	return err
}

const deleteShip = `-- name: DeleteShip :exec
DELETE FROM ships WHERE id = $1
`

func (q *Queries) DeleteShip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShip, id)
	return err
}

const getSeatimeByUserId = `-- name: GetSeatimeByUserId :many
SELECT 
    s.id, s.user_id, s.ship_id, s.voyage_type_id, s.created_at, s.updated_at, s.start_date, s.start_location, s.end_date, s.end_location, s.total_days, s.company, s.capacity, s.is_watchkeeping, 
    sh.name as ship_name, 
    sh.imo_number as ship_imo,
    sh.gt as ship_gt,
    sh.flag as ship_flag,
    sh.propulsion_power as ship_propulsion_power,
    sh.ship_type_id as ship_type_id,
    sh.created_at as ship_created_at,
    sh.updated_at as ship_updated_at,
    sh.status as ship_status,
    sh.created_by as ship_created_by,
    st.name as ship_type_name,
    vt.name as voyage_type_name
FROM seatime s
JOIN ships sh ON s.ship_id = sh.id
JOIN ship_types st ON sh.ship_type_id = st.id
JOIN voyage_types vt ON s.voyage_type_id = vt.id
WHERE s.user_id = $1
ORDER BY s.start_date DESC
`

type GetSeatimeByUserIdRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ShipID              uuid.UUID
	VoyageTypeID        uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	StartDate           time.Time
	StartLocation       string
	EndDate             time.Time
	EndLocation         string
	TotalDays           int32
	Company             string
	Capacity            string
	IsWatchkeeping      bool
	ShipName            string
	ShipImo             string
	ShipGt              int32
	ShipFlag            string
	ShipPropulsionPower sql.NullInt32
	ShipTypeID          uuid.UUID
	ShipCreatedAt       time.Time
	ShipUpdatedAt       time.Time
	ShipStatus          string
	ShipCreatedBy       uuid.NullUUID
	ShipTypeName        string
	VoyageTypeName      string
}

func (q *Queries) GetSeatimeByUserId(ctx context.Context, userID uuid.UUID) ([]GetSeatimeByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeatimeByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatimeByUserIdRow
	for rows.Next() {
		var i GetSeatimeByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShipID,
			&i.VoyageTypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
			&i.StartLocation,
			&i.EndDate,
			&i.EndLocation,
			&i.TotalDays,
			&i.Company,
			&i.Capacity,
			&i.IsWatchkeeping,
			&i.ShipName,
			&i.ShipImo,
			&i.ShipGt,
			&i.ShipFlag,
			&i.ShipPropulsionPower,
			&i.ShipTypeID,
			&i.ShipCreatedAt,
			&i.ShipUpdatedAt,
			&i.ShipStatus,
			&i.ShipCreatedBy,
			&i.ShipTypeName,
			&i.VoyageTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatimePeriodTypes = `-- name: GetSeatimePeriodTypes :many
SELECT id, name, description FROM seatime_period_types ORDER BY name
`

func (q *Queries) GetSeatimePeriodTypes(ctx context.Context) ([]SeatimePeriodType, error) {
	rows, err := q.db.QueryContext(ctx, getSeatimePeriodTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SeatimePeriodType
	for rows.Next() {
		var i SeatimePeriodType
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeatimePeriods = `-- name: GetSeatimePeriods :many
SELECT sp.id, sp.seatime_id, sp.period_type_id, sp.start_date, sp.end_date, sp.days, sp.remarks, spt.name as period_type_name
FROM seatime_periods sp
JOIN seatime_period_types spt ON sp.period_type_id = spt.id
WHERE sp.seatime_id = $1
`

type GetSeatimePeriodsRow struct {
	ID             uuid.UUID
	SeatimeID      uuid.UUID
	PeriodTypeID   uuid.UUID
	StartDate      time.Time
	EndDate        time.Time
	Days           int32
	Remarks        sql.NullString
	PeriodTypeName string
}

func (q *Queries) GetSeatimePeriods(ctx context.Context, seatimeID uuid.UUID) ([]GetSeatimePeriodsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeatimePeriods, seatimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeatimePeriodsRow
	for rows.Next() {
		var i GetSeatimePeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeatimeID,
			&i.PeriodTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.Days,
			&i.Remarks,
			&i.PeriodTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShipById = `-- name: GetShipById :one
SELECT s.id, s.created_at, s.updated_at, s.name, s.ship_type_id, s.imo_number, s.gt, s.flag, s.propulsion_power, s.status, s.created_by, st.name as ship_type_name
FROM ships s
JOIN ship_types st ON s.ship_type_id = st.id
WHERE s.id = $1
`

type GetShipByIdRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
	ShipTypeName    string
}

func (q *Queries) GetShipById(ctx context.Context, id uuid.UUID) (GetShipByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getShipById, id)
	var i GetShipByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShipTypeID,
		&i.ImoNumber,
		&i.Gt,
		&i.Flag,
		&i.PropulsionPower,
		&i.Status,
		&i.CreatedBy,
		&i.ShipTypeName,
	)
	return i, err
}

const getShipByImo = `-- name: GetShipByImo :one
SELECT s.id, s.created_at, s.updated_at, s.name, s.ship_type_id, s.imo_number, s.gt, s.flag, s.propulsion_power, s.status, s.created_by, st.name as ship_type_name
FROM ships s
JOIN ship_types st ON s.ship_type_id = st.id
WHERE s.imo_number = $1
`

type GetShipByImoRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
	ShipTypeName    string
}

func (q *Queries) GetShipByImo(ctx context.Context, imoNumber string) (GetShipByImoRow, error) {
	row := q.db.QueryRowContext(ctx, getShipByImo, imoNumber)
	var i GetShipByImoRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShipTypeID,
		&i.ImoNumber,
		&i.Gt,
		&i.Flag,
		&i.PropulsionPower,
		&i.Status,
		&i.CreatedBy,
		&i.ShipTypeName,
	)
	return i, err
}

const getShipTypes = `-- name: GetShipTypes :many
SELECT id, name, description FROM ship_types ORDER BY name
`

func (q *Queries) GetShipTypes(ctx context.Context) ([]ShipType, error) {
	rows, err := q.db.QueryContext(ctx, getShipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipType
	for rows.Next() {
		var i ShipType
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShips = `-- name: GetShips :many
SELECT s.id, s.created_at, s.updated_at, s.name, s.ship_type_id, s.imo_number, s.gt, s.flag, s.propulsion_power, s.status, s.created_by, st.name as ship_type_name
FROM ships s
JOIN ship_types st ON s.ship_type_id = st.id
`

type GetShipsRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
	ShipTypeName    string
}

func (q *Queries) GetShips(ctx context.Context) ([]GetShipsRow, error) {
	rows, err := q.db.QueryContext(ctx, getShips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShipsRow
	for rows.Next() {
		var i GetShipsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ShipTypeID,
			&i.ImoNumber,
			&i.Gt,
			&i.Flag,
			&i.PropulsionPower,
			&i.Status,
			&i.CreatedBy,
			&i.ShipTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShipsForUser = `-- name: GetShipsForUser :many
SELECT s.id, s.created_at, s.updated_at, s.name, s.ship_type_id, s.imo_number, s.gt, s.flag, s.propulsion_power, s.status, s.created_by, st.name as ship_type_name
FROM ships s
JOIN ship_types st ON s.ship_type_id = st.id
WHERE s.status = 'approved' OR s.created_by = $1
`

type GetShipsForUserRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
	Status          string
	CreatedBy       uuid.NullUUID
	ShipTypeName    string
}

func (q *Queries) GetShipsForUser(ctx context.Context, createdBy uuid.NullUUID) ([]GetShipsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getShipsForUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShipsForUserRow
	for rows.Next() {
		var i GetShipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ShipTypeID,
			&i.ImoNumber,
			&i.Gt,
			&i.Flag,
			&i.PropulsionPower,
			&i.Status,
			&i.CreatedBy,
			&i.ShipTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoyageTypes = `-- name: GetVoyageTypes :many
SELECT id, name, description FROM voyage_types ORDER BY name
`

func (q *Queries) GetVoyageTypes(ctx context.Context) ([]VoyageType, error) {
	rows, err := q.db.QueryContext(ctx, getVoyageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoyageType
	for rows.Next() {
		var i VoyageType
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShip = `-- name: UpdateShip :one
UPDATE ships
SET name = $2, ship_type_id = $3, imo_number = $4, gt = $5, flag = $6, propulsion_power = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, ship_type_id, imo_number, gt, flag, propulsion_power, status, created_by
`

type UpdateShipParams struct {
	ID              uuid.UUID
	Name            string
	ShipTypeID      uuid.UUID
	ImoNumber       string
	Gt              int32
	Flag            string
	PropulsionPower sql.NullInt32
}

func (q *Queries) UpdateShip(ctx context.Context, arg UpdateShipParams) (Ship, error) {
	row := q.db.QueryRowContext(ctx, updateShip,
		arg.ID,
		arg.Name,
		arg.ShipTypeID,
		arg.ImoNumber,
		arg.Gt,
		arg.Flag,
		arg.PropulsionPower,
	)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShipTypeID,
		&i.ImoNumber,
		&i.Gt,
		&i.Flag,
		&i.PropulsionPower,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}

const updateShipReferences = `-- name: UpdateShipReferences :exec
UPDATE seatime SET ship_id = $2 WHERE ship_id = $1
`

type UpdateShipReferencesParams struct {
	ShipID   uuid.UUID
	ShipID_2 uuid.UUID
}

func (q *Queries) UpdateShipReferences(ctx context.Context, arg UpdateShipReferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateShipReferences, arg.ShipID, arg.ShipID_2)
	return err
}

const updateShipStatus = `-- name: UpdateShipStatus :one
UPDATE ships
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, name, ship_type_id, imo_number, gt, flag, propulsion_power, status, created_by
`

type UpdateShipStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateShipStatus(ctx context.Context, arg UpdateShipStatusParams) (Ship, error) {
	row := q.db.QueryRowContext(ctx, updateShipStatus, arg.ID, arg.Status)
	var i Ship
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ShipTypeID,
		&i.ImoNumber,
		&i.Gt,
		&i.Flag,
		&i.PropulsionPower,
		&i.Status,
		&i.CreatedBy,
	)
	return i, err
}
