// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, forename, surname, nationality)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, forename, surname, email, nationality
`

type CreateUserParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	Forename    sql.NullString
	Surname     sql.NullString
	Nationality sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.Forename,
		arg.Surname,
		arg.Nationality,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, forename, surname, email, nationality
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, forename, surname, email, nationality
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    forename = COALESCE($2, forename),
    surname = COALESCE($3, surname),
    nationality = COALESCE($4, nationality),
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, forename, surname, email, nationality
`

type UpdateUserParams struct {
	ID          uuid.UUID
	Forename    sql.NullString
	Surname     sql.NullString
	Nationality sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Forename,
		arg.Surname,
		arg.Nationality,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
	)
	return i, err
}
