// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, forename, surname, nationality, email_consent, email_consent_timestamp, email_consent_version, email_consent_source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at, forename, surname, email, nationality, email_consent, email_consent_timestamp, email_consent_version, email_consent_source
`

type CreateUserParams struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	Email                 string
	Forename              sql.NullString
	Surname               sql.NullString
	Nationality           sql.NullString
	EmailConsent          bool
	EmailConsentTimestamp sql.NullTime
	EmailConsentVersion   sql.NullString
	EmailConsentSource    sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.Forename,
		arg.Surname,
		arg.Nationality,
		arg.EmailConsent,
		arg.EmailConsentTimestamp,
		arg.EmailConsentVersion,
		arg.EmailConsentSource,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
		&i.EmailConsent,
		&i.EmailConsentTimestamp,
		&i.EmailConsentVersion,
		&i.EmailConsentSource,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, forename, surname, email, nationality, email_consent, email_consent_timestamp, email_consent_version, email_consent_source
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
		&i.EmailConsent,
		&i.EmailConsentTimestamp,
		&i.EmailConsentVersion,
		&i.EmailConsentSource,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, forename, surname, email, nationality, email_consent, email_consent_timestamp, email_consent_version, email_consent_source
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
		&i.EmailConsent,
		&i.EmailConsentTimestamp,
		&i.EmailConsentVersion,
		&i.EmailConsentSource,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    forename = COALESCE($2, forename),
    surname = COALESCE($3, surname),
    nationality = COALESCE($4, nationality),
    email_consent = COALESCE($5, email_consent),
    email_consent_timestamp = COALESCE($6, email_consent_timestamp),
    email_consent_version = COALESCE($7, email_consent_version),
    email_consent_source = COALESCE($8, email_consent_source),
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, forename, surname, email, nationality, email_consent, email_consent_timestamp, email_consent_version, email_consent_source
`

type UpdateUserParams struct {
	ID                    uuid.UUID
	Forename              sql.NullString
	Surname               sql.NullString
	Nationality           sql.NullString
	EmailConsent          sql.NullBool
	EmailConsentTimestamp sql.NullTime
	EmailConsentVersion   sql.NullString
	EmailConsentSource    sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Forename,
		arg.Surname,
		arg.Nationality,
		arg.EmailConsent,
		arg.EmailConsentTimestamp,
		arg.EmailConsentVersion,
		arg.EmailConsentSource,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Forename,
		&i.Surname,
		&i.Email,
		&i.Nationality,
		&i.EmailConsent,
		&i.EmailConsentTimestamp,
		&i.EmailConsentVersion,
		&i.EmailConsentSource,
	)
	return i, err
}
