package certificates

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/adamjames870/seacert/internal/database/sqlc"
	"github.com/adamjames870/seacert/internal/dto"
	"github.com/google/generative-ai-go/genai"
)

const basePrompt = `Extract certificate details from this image. 
Return strictly JSON. 
If a field is not visible, return null.
Use the following JSON structure:
{
  "cert-type-name": "string",
  "cert-number": "string",
  "issuer-name": "string",
  "issued-date": "YYYY-MM-DD",
  "expiry-date": "YYYY-MM-DD",
  "remarks": "string",
  "cert-type-id": "string",
  "issuer-id": "string"
}`

func ExtractCertificateData(ctx context.Context, client *genai.Client, fileBytes []byte, mimeType string, certTypes []sqlc.CertificateType, issuers []sqlc.Issuer) (*dto.ExtractedCertificate, error) {
	if client == nil {
		return nil, fmt.Errorf("Gemini client is not initialized")
	}

	var promptBuilder strings.Builder
	promptBuilder.WriteString(basePrompt)
	promptBuilder.WriteString("\n\n")
	promptBuilder.WriteString("Please match the 'issuer-name' and 'cert-type-name' against these known lists. If a match is found, return the ID from the list in 'issuer-id' or 'cert-type-id' respectively.\n")

	promptBuilder.WriteString("\nKnown Certificate Types:\n")
	for _, ct := range certTypes {
		promptBuilder.WriteString(fmt.Sprintf("- %s (ID: %s)\n", ct.Name, ct.ID.String()))
	}

	promptBuilder.WriteString("\nKnown Issuers:\n")
	for _, i := range issuers {
		promptBuilder.WriteString(fmt.Sprintf("- %s (ID: %s)\n", i.Name, i.ID.String()))
	}

	model := client.GenerativeModel("gemini-flash-latest")

	// Set the response MIME type to application/json to ensure structured output
	model.ResponseMIMEType = "application/json"

	prompt := []genai.Part{
		genai.Blob{
			MIMEType: mimeType,
			Data:     fileBytes,
		},
		genai.Text(promptBuilder.String()),
	}

	resp, err := model.GenerateContent(ctx, prompt...)
	if err != nil {
		return nil, fmt.Errorf("failed to generate content: %w", err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no content generated by Gemini")
	}

	part := resp.Candidates[0].Content.Parts[0]
	text, ok := part.(genai.Text)
	if !ok {
		return nil, fmt.Errorf("unexpected response part type: %T", part)
	}

	var extracted dto.ExtractedCertificate
	if err := json.Unmarshal([]byte(text), &extracted); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Gemini response: %w. Response: %s", err, string(text))
	}

	return &extracted, nil
}
